### ISSUE TITLE
Creating package atlas_core_description

### ISSUE THREAD

**Issue by bernardomig** [lardemua/atlascar2#2]
This package should contain all the urdf/xacro files to describe the car.

See [this](https://github.com/bernardomig/atlas-augmented-perception/tree/master/atlas_perception_description) for inspiration.

**Comment by danifpdra** [comment]
[frames.pdf](https://github.com/lardemua/atlas-core/files/3028945/frames.pdf)

![image](https://user-images.githubusercontent.com/11350998/55322270-c8e60200-5473-11e9-95b4-5dd4607f6f47.png)

Tf frame tree

**Comment by danifpdra** [comment]
![image](https://user-images.githubusercontent.com/47574905/55322473-604b5500-5474-11e9-9115-0b4aeabddb82.png)

**Comment by danifpdra** [comment]
![](https://i.imgur.com/IWZVzw9.jpg)
![](https://i.imgur.com/3vBPCzi.jpg)

**Comment by bernardomig** [comment]
Added first draft of the tree acording to the specs.

In rviz, look like this:

![Screenshot from 2019-04-01 18-08-27](https://user-images.githubusercontent.com/6053181/55346027-56901480-54a9-11e9-8218-2707d7b2d328.png)

TODO: still missing the laser frames. Waiting for the calibration data of these joints.

**Comment by danifpdra** [comment]
![Screenshot from 2019-04-03 10-55-56](https://user-images.githubusercontent.com/47574905/55470340-56099200-55ff-11e9-9fab-9839496fecec.png)
![Screenshot from 2019-04-03 10-56-13](https://user-images.githubusercontent.com/47574905/55470343-56099200-55ff-11e9-9324-58a154e05d94.png)
![Screenshot from 2019-04-03 10-56-23](https://user-images.githubusercontent.com/47574905/55470344-56099200-55ff-11e9-8bcc-1cce52b760b5.png)
![Screenshot from 2019-04-03 10-56-32](https://user-images.githubusercontent.com/47574905/55470346-56a22880-55ff-11e9-978b-6e896bd283ac.png)
![Screenshot from 2019-04-03 10-56-42](https://user-images.githubusercontent.com/47574905/55470348-56a22880-55ff-11e9-8b88-075961ea79fb.png)

description of existing tf frame data

**Comment by miguelriemoliveira** [comment]
Hi @danifpdra ,

Just a tip: usually we is done is to cpy the text, not the images onto the issues.

**Comment by danifpdra** [comment]
Sorry, here it is:

---
transforms: 
  - 
    header: 
      seq: 0
      stamp: 
        secs: 1526660606
        nsecs: 475882697
      frame_id: "car_center"
    child_frame_id: "moving_axis"
    transform: 
      translation: 
        x: 1.75
        y: 0.0
        z: -0.1
      rotation: 
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
---
transforms: 
  - 
    header: 
      seq: 0
      stamp: 
        secs: 1526660606
        nsecs: 475882697
      frame_id: "moving_axis"
    child_frame_id: "lms151_E"
    transform: 
      translation: 
        x: -0.101511643826
        y: -0.767737698645
        z: 0.353534532466
      rotation: 
        x: -0.0148663329343
        y: -0.000191825062115
        z: -0.415668438171
        w: 0.90939469146
---
transforms: 
  - 
    header: 
      seq: 0
      stamp: 
        secs: 1526660606
        nsecs: 475882697
      frame_id: "lms151_E"
    child_frame_id: "lms151_D"
    transform: 
      translation: 
        x: -1.09520995617
        y: 1.01234996319
        z: 0.0670335963368
      rotation: 
        x: 0.0218314712385
        y: 0.00628061035926
        z: 0.74070749896
        w: 0.671443476237
---
transforms: 
  - 
    header: 
      seq: 0
      stamp: 
        secs: 1526660606
        nsecs: 475882697
      frame_id: "lms151_E"
    child_frame_id: "ldmrs3"
    transform: 
      translation: 
        x: -0.51847499609
        y: 0.588346004486
        z: -0.331277996302
      rotation: 
        x: 0.0148663327614
        y: 0.000191825440531
        z: 0.415668438177
        w: 0.90939469146
---
transforms: 
  - 
    header: 
      seq: 0
      stamp: 
        secs: 1526660606
        nsecs: 475882697
      frame_id: "lms151_E"
    child_frame_id: "ldmrs2"
    transform: 
      translation: 
        x: -0.51847499609
        y: 0.588346004486
        z: -0.331277996302
      rotation: 
        x: 0.00906124595574
        y: 0.0128889394238
        z: 0.415835486904
        w: 0.909303369011
---
transforms: 
  - 
    header: 
      seq: 0
      stamp: 
        secs: 1526660606
        nsecs: 475882697
      frame_id: "lms151_E"
    child_frame_id: "ldmrs1"
    transform: 
      translation: 
        x: -0.51847499609
        y: 0.588346004486
        z: -0.331277996302
      rotation: 
        x: 0.0119640809148
        y: 0.00654054182055
        z: 0.415762094369
        w: 0.90937119097
---
transforms: 
  - 
    header: 
      seq: 0
      stamp: 
        secs: 1526660606
        nsecs: 475882697
      frame_id: "lms151_E"
    child_frame_id: "ldmrs0"
    transform: 
      translation: 
        x: -0.51847499609
        y: 0.588346004486
        z: -0.331277996302
      rotation: 
        x: 0.00615796936436
        y: 0.0192367088383
        z: 0.415888612203
        w: 0.909191228888
---
transforms: 
  - 
    header: 
      seq: 0
      stamp: 
        secs: 1526660606
        nsecs: 485939475
      frame_id: "/map"
    child_frame_id: "/map__identity"
    transform: 
      translation: 
        x: 0.0
        y: 0.0
        z: 0.0
      rotation: 
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
---

**Comment by miguelriemoliveira** [comment]
Looks much better! ... And we can copy paste!
