### ISSUE TITLE
Step 4 in readme file

### ISSUE THREAD

**Issue by Sarxell** [lardemua/atlascar2#20]
no passo 4 do readme:
**Step 4:** Plug the eduroam (UA) ethernet cable (the cable is outside the atlascar2) to the atlas computer (on the figure port).
 
Este passo só é possível quando o carro se encontra parado, sendo assim não é preciso ligar nada caso se vá conduzir?
@miguelriemoliveira

**Comment by miguelriemoliveira** [comment]
Olá @Sarxell e @vitoruapt ,

realmente neste caso não faz sentido quando o carro está a andar. Só quando estamos a fazer experiências parados.

Outra nota: a rede por cabo acho que não se chama eduroam.
