### ISSUE TITLE
test of the LIDAR Sick LMS151

### ISSUE THREAD

**Issue by Sarxell** [lardemua/atlascar2#21]
Olá @vitoruapt e @miguelriemoliveira , 
Dificuldades e progressos no teste do LIDAR 2D LMS151.

**Comment by Sarxell** [comment]
Boa tarde professores,
estou com um problema em relação a ver a informação do lidar.
Eu instalei os drivers e consegui colocar o launch file a correr só com o lidar. No entanto este não me envia dados nenhuns.
![Screenshot from 2021-12-13 17-21-09](https://user-images.githubusercontent.com/92535336/145861466-37910e9f-ecc9-4616-a6ed-8e165c0f1d16.png)

Passado um tempo dá este aviso:
![Screenshot from 2021-12-13 17-44-45](https://user-images.githubusercontent.com/92535336/145862089-260e7024-cdd4-479e-82d1-a4ee959902ab.png)

Eu tenho de ligar-me á rede ethernet do atlascar? Preciso de mudar algo no ip do computador?

**Comment by miguelriemoliveira** [comment]
Olá @Sarxell ,

Preliminary topic -------------

There is a better way to format the issues. Take a look here

https://github.com/miguelriemoliveira/simpleBot/issues/3

The first post is from Analtino, then the second one I was trying to show them how to better forma an issue.

One thing is that I cannot see the images.

--------------------------

About the issue, can you ping the lidar? What is the lidar's ip address and your computer's ipaddress?

**Comment by Sarxell** [comment]
when i run : 
`ping 198.168.0.134`

I get: 
`From 198.168.0.134 icmp_seq=1 Destination Host Unreachable
From 198.168.0.134 icmp_seq=4 Destination Host Unreachable
From 198.168.0.134 icmp_seq=2 Destination Host Unreachable
From 198.168.0.134 icmp_seq=3 Destination Host Unreachable
...`

to see my ip:
when I run : 
`curl ifconfig.me` 

i receive:
`193.137.168.32`

when I run:
`ifconfig -a`

I receive the following networks:
`eno1:` flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.0.5  netmask 255.255.255.0  broadcast 192.168.0.255
        inet6 fe80::3b46:d1c3:2405:2f95  prefixlen 64  scopeid 0x20<link>
        ether 30:9c:23:92:c3:23  txqueuelen 1000  (Ethernet)
        RX packets 37  bytes 4272 (4.2 KB)
        RX errors 2  dropped 0  overruns 0  frame 1
        TX packets 2279  bytes 372099 (372.0 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 16  memory 0xba200000-ba220000  

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 79184  bytes 13897139 (13.8 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 79184  bytes 13897139 (13.8 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlp59s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.42.178  netmask 255.255.224.0  broadcast 192.168.63.255
        inet6 fe80::c3ab:9533:976e:4720  prefixlen 64  scopeid 0x20<link>
        ether 00:e1:8c:c9:c7:1e  txqueuelen 1000  (Ethernet)
        RX packets 114522  bytes 92783877 (92.7 MB)
        RX errors 0  dropped 53  overruns 0  frame 0
        TX packets 70327  bytes 17869674 (17.8 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0 `

**Comment by Sarxell** [comment]
In the readme file in "known problems" there is "Need to connect 2 cables: for ua ethernet and router set the router ipv4 automiatic" I only connected the LIDAR cable to my pc, do I need to have 2 ethernet ports?

**Comment by miguelriemoliveira** [comment]
Hi @Sarxell ,

I think we should zoom. When can you be near the car for a meeting?

**Comment by Sarxell** [comment]
Yes, I'm available all day tomorrow and wednesday.

**Comment by miguelriemoliveira** [comment]
Hi @Sarxell ,

ok, lets talk tomorrow at 9h by zoom? You should be near the car.

**Comment by Sarxell** [comment]
Ok!

**Comment by Sarxell** [comment]
Do I use the zoom meeting of the TP from PSR?

**Comment by miguelriemoliveira** [comment]
With the command 

    ifconfig

The output is:

```bash
lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 1442  bytes 119916 (119.9 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1442  bytes 119916 (119.9 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlp0s20f3: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.0.67  netmask 255.255.255.0  broadcast 192.168.0.255
        inet6 fe80::d566:649f:fe86:3dcb  prefixlen 64  scopeid 0x20<link>
        ether 04:6c:59:d7:b6:3a  txqueuelen 1000  (Ethernet)
        RX packets 93011  bytes 84391806 (84.3 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 76244  bytes 39522998 (39.5 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

example with python ...

```python
    marker_array = MarkerArray()
    for marker in graphics['ros']['MarkersLabeled'].markers:
        print(marker.header.frame_id)
        prefix = marker.header.frame_id[:3]
        if prefix == 'c' + str(selected_collection_key) + '_':
            marker_array.markers.append(marker)
```

**Comment by Sarxell** [comment]
with the command

    ifconfig

The output is:

```bash
eno1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.0.2  netmask 255.255.255.0  broadcast 192.168.0.255
        inet6 fe80::329c:23ff:fe92:c323  prefixlen 64  scopeid 0x20<link>
        ether 30:9c:23:92:c3:23  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 415  bytes 41666 (41.6 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 16  memory 0xba200000-ba220000  

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 4286  bytes 577919 (577.9 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 4286  bytes 577919 (577.9 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlp59s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.42.178  netmask 255.255.224.0  broadcast 192.168.63.255
        inet6 fe80::c3ab:9533:976e:4720  prefixlen 64  scopeid 0x20<link>
        ether 00:e1:8c:c9:c7:1e  txqueuelen 1000  (Ethernet)
        RX packets 83550  bytes 69886170 (69.8 MB)
        RX errors 0  dropped 11  overruns 0  frame 0
        TX packets 51239  bytes 29944545 (29.9 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

**Comment by Sarxell** [comment]
After the problem caused by windows (DO NOT USE THE CAMERAS IN WINDOWS!) the left and right LIDAR LMS151 worked well in rviz. 

**left laser**
![Screenshot from 2021-12-16 16-14-55](https://user-images.githubusercontent.com/92535336/146653618-2d03709d-ec70-43f7-8794-bd6fbe02a067.png)

**right laser**
![Screenshot from 2021-12-16 16-15-35](https://user-images.githubusercontent.com/92535336/146653621-a2586411-9ab2-419d-bc32-9d5444435ff8.png)

**Comment by miguelriemoliveira** [comment]
Great. So I would say you can create new version of the readme. Once its done let me know and I will test it.

**Comment by Sarxell** [comment]
I tried to create a new file but I don't have writing permission in this repository

**Comment by miguelriemoliveira** [comment]
resolvido.


*  Miguel Riem de Oliveira                                             *
Diretor de curso Mestrado Eng. Automação Industrial
email:    ***@***.***    |    ***@***.***
zoom: https://videoconf-colibri.zoom.us/j/7155402102
office: 22.2.18                 |    ext: 23887
Dep. de Engenharia Mecânica, Universidade de Aveiro
*Campus Universitário de Santiago, 3810-193  Portugal*

**Comment by Sarxell** [comment]
Good morning @miguelriemoliveira ,
The parts that I changed in the Readme are in the file Readme_update.md

If there is something that may be better other way let me know and I will change it.

Boas festas!

**Comment by miguelriemoliveira** [comment]
Hi @Sarxell ,

you can just change the readme.md directly. That's why we have the git version control.

I will look at this later on. You should now focus on having some document with the state of the art to show us at the beginning / middle of january.

Boas Festas, bom trabalho,
Miguel

**Comment by miguelriemoliveira** [comment]
Hi @Sarxell ,

I just looked into the new readme. It looks much better. Congratullations!
