### ISSUE TITLE
Test of the point grey flea 2 camera

### ISSUE THREAD

**Issue by Sarxell** [lardemua/atlascar2#22]
Olá @vitoruapt e @miguelriemoliveira , 
Dificuldades e progressos no teste da câmara.

**Comment by Sarxell** [comment]
Boa tarde professores,
Sobre a camera deu-me o seguinte erro ( depois de ter instalado os drivers):

![Screenshot from 2021-12-13 18-01-54](https://user-images.githubusercontent.com/92535336/145865193-8e149847-09e9-4ee3-9e14-bc5ea1f2de0f.png)

Neste caso eu encontrei que podem ter dado update aos launch files e isto já não ser necessário, eu comentei e consegui colocar o launch file a correr. No entanto deu-me outro erro:
![Screenshot from 2021-12-13 18-09-12](https://user-images.githubusercontent.com/92535336/145865542-af070f77-30ec-4d45-9f91-3c4a5d618ae5.png)

Eu utilizei o comando : 
`rosrun pointgrey_camera_driver list_cameras` 
o qual nao detetou nenhuma camera, pode ser uma das razões para este problema

**Comment by miguelriemoliveira** [comment]
Olá @Sarxell ,

quanto à formatação, o mesmo comentário que em #21 .

Como são câmaras ethernet faço a mesma pergunta: qual é  o ip da câmara, o seu ip e se consegue fazer ping.

**Comment by Sarxell** [comment]
Exatamente igual ao que acontece no lidar, eu já tentei mudar o ip estático, mas como ainda só tinha feito isso no windows posso ter mudado de maneira errada

**Comment by Sarxell** [comment]
After using mode 0 in the camera and changing a little the values in the camera settings it finally worked
![Screenshot from 2021-12-16 16-36-32](https://user-images.githubusercontent.com/92535336/146421450-7deab873-584b-42de-8873-696cd046abcd.png)

It has a warning that says:
`Default Linux receive buffer setting is lower than expected` 
I still need to test with rviz and try to change the packet resend and size because the frame rate is very slow

**Comment by miguelriemoliveira** [comment]
Ok, also good news. Can you document the procedure? Does it work always?

**Comment by Sarxell** [comment]
I tried this method three or four times and it worked all of them. 
The procedure was:

1. Before opening the flycap camera, use the terminal
2. Write the command `roslaunch pointgrey_camera_driver camera.launch packet_resend:=false` to launch the camera
3. Stop roslaunch
4. Open the flycap camera and the camera is working

**Comment by miguelriemoliveira** [comment]
OK, thanks.

**Comment by Sarxell** [comment]
Hi @miguelriemoliveira ,

Today decided to test the cameras in rviz, with that I had to resolve the following error:

```bash 
[ERROR] [1512118059.821921194]: Reconfigure Callback failed with error: PointGreyCamera::SetGigEConfig could not set GigE settings (packet resend) | FlyCapture2::ErrorType 7 Packet resend is not supported.
```

I found that it envolved the `PointGreyCamera.cpp` in these lines:

```c++
        gigeconfig.enablePacketResend = true;
        error = cam.SetGigEConfig(&gigeconfig);
        PointGreyCamera::handleError("PointGreyCamera::SetGigEConfig could not set GigE settings (packet resend)", error);
```

I changed the `gigeconfig.enablePacketResend` value to `false`. The error disappeared and rviz and rqt_image_view started working 
![Screenshot from 2022-01-18 15-48-18](https://user-images.githubusercontent.com/92535336/149974368-910a9432-53dc-4394-9b48-6ba6497638d9.png)
![Screenshot from 2022-01-18 15-49-18](https://user-images.githubusercontent.com/92535336/149974371-c0932207-69a7-439a-adf1-9a34d125410b.png)

I will try to update today the readme in more detail.

**Comment by Sarxell** [comment]
Olá @miguelriemoliveira ,

Right now I'm testing the atlascar2 cameras. As it can be seen in the photo below they are working in the spinview api
![Screenshot from 2022-03-21 15-50-48](https://user-images.githubusercontent.com/92535336/159301570-3259ec3f-ee80-4c76-a1f9-a69e80827429.png)

But in the flycap api they don't work
![Screenshot from 2022-03-21 15-55-33](https://user-images.githubusercontent.com/92535336/159301838-fc5d1ae9-d164-4777-bdef-cac0297d86d1.png)


Right now there exists a new driver for the cameras that its this one: http://wiki.ros.org/spinnaker_sdk_camera_driver

With only one camera connected, the flycap works well, but with more than one I can ping, see them in the spinview but not in the flycap

I can try create a new launch file using the spinnaker driver and see if they work better than with the flycapture

A note: when I use `updatorgui` to force the IP the cameras start working but one of them disappears, looks like the node merges and we can't see the image

**Comment by miguelriemoliveira** [comment]
Hi @Sarxell ,

if it works all the time with our launch files I don't care that it does not work well with flycapture ...

**Comment by Sarxell** [comment]
The problem is that when I run the launch files, it appears the same error that in the flycapture, that it doens't find any cameras... But using the spinview everything looks fine, that's my confusion... When I'm only using one camera it worked on both as well as with the launch files... Tomorrow I will try it again and give an update

**Comment by Sarxell** [comment]
Hi @miguelriemoliveira ,
So it was my bad , one of the cameras had a mask of the persistent Id of 255.255.0.0 which doesn't work, so I went to windows and I configured the right mask in that camera and now it's working

**Comment by miguelriemoliveira** [comment]
Great!
