### ISSUE TITLE
test of the LIDAR Sick LD MRS

### ISSUE THREAD

**Issue by Sarxell** [lardemua/atlascar2#23]
Olá @vitoruapt e @miguelriemoliveira , 
Dificuldades e progressos no teste do LIDAR LD MRS.

**Comment by Sarxell** [comment]
Funnily enough, after repairing the problem that windows made, this one was the easiest to test. After following the installation readme: [https://github.com/SICKAG/sick_ldmrs_laser](url) I launched the file and could see in rviz the following pointcloud2:
![Screenshot from 2021-12-16 16-12-58](https://user-images.githubusercontent.com/92535336/146420953-a01b51a6-41f6-45fa-ba9b-2ce7b3afd109.png)

**Comment by miguelriemoliveira** [comment]
Hi @Sarxell ,

good news. I remember it collided with the other ros packages. In any case, for now I would close the issue. If we need we may come back to it later.
