### ISSUE TITLE
ATLAS PC boots very slow

### ISSUE THREAD

**Issue by Sarxell** [lardemua/atlascar2#27]
The boot is very slow
`systemd-analyze` gives the following output:

`Startup finished in 2.079s (kernel) + 5min 17.273s (userspace) = 5min 19.353s
graphical.target reached after 5min 17.236s in userspace`

The userspace is taking too long to start, I will try to change this and put the steps I make.

**Comment by Sarxell** [comment]
So I'm using this [tutorial](https://linuxstoney.com/diagnose-and-fix-slow-boot-on-ubuntu/).

**method 1:**  Didn't work. `systemd-analyze` gave the following output:

`Startup finished in 2.156s (kernel) + 5min 19.176s (userspace) = 5min 21.333s 
graphical.target reached after 5min 19.160s in userspace
`

Even worse than the first time!

**method 2:** This method worked really well! `systemd-analyze` gave the following output:
Startup finished in 2.131s (kernel) + 1min 45.568s (userspace) = 1min 47.699s 
graphical.target reached after 1min 41.196s in userspace

Which is 4 minutes faster.

**Comment by Sarxell** [comment]
I think the main problem right now is the BIOS taking (also) very long to load, I will check it too.

**Comment by Sarxell** [comment]
I decided to do **method 3** from the tutorial.

Right now the boot is moderately fast compared with 5 minutes:
`Startup finished in 2.124s (kernel) + 18.435s (userspace) = 20.560s 
graphical.target reached after 18.417s in userspace
`

**Comment by Sarxell** [comment]
With the BIOS, the pc starts after approximately 2 minutes. It's better than before but still a little slow.. For a better performance in the BIOS the last thing is update it but I think that can be risky since if done incorrectly can mess up the pc

**Comment by miguelriemoliveira** [comment]
Hi @Sarxell ,

4 mins faster is already a lot. I would leave it as is.

**Comment by Sarxell** [comment]
Okay!
