### ISSUE TITLE
Changing ackermann_steering_controller

### ISSUE THREAD

**Issue by Sarxell** [lardemua/atlascar2#29]
In order to be able to test the python node that will test the odometry, we need to receive the speed and steering angle of the vehicle from the ackermann_steering_controller.cpp.

**Comment by miguelriemoliveira** [comment]
The ackermann_steering_controller should run as a gazebo plugin and publish a [Ackerman ros msg](http://docs.ros.org/en/api/ackermann_msgs/html/msg/AckermannDriveStamped.html)

**Comment by manuelgitgomes** [comment]
Done
