### ISSUE TITLE
Add the base sensor drivers to atlas2-sensors

### ISSUE THREAD

**Issue by bernardomig** [lardemua/atlascar2#3]
The sensor driver packages should be added to the folder `atlas2-sensors`, as submodules, namely:

- [ ] The two Lidar LMS 1xx
- [ ] 2.5 Lidar LMS 151
- [ ] GPS Novatel 
- [ ] Frontal Camera Flea2

**Comment by miguelriemoliveira** [comment]
This was done in a completely different way but it remains undocumented :-(
