### ISSUE TITLE
Consistency between simulation and live mode

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atlascar2#35]
Following #32 and https://github.com/lardemua/atom/issues/425 we found that the topic names of the atlascar2 in the simulation and the live mode (with real sensors) is not consistent.

This should be altered so that the change from simulation to live is seamless to other nodes.

We could also try to add the 2D lidar sensors and even the four layer sick lrms sensor to the simulation so we have a complete simulation of the atlascar2, even though for now we won't calibrate those sensors. For 2d lidars gazebo already has models of the  sensors (#33), but perhaps for the lrms we have to create our own (#34).

You can change the topic names of the live mode or the simulation. I liked that all the topics in the simulation were under the atlascar2 namespace. Perhaps you can articulate with @Sarxell because she did the live mode.

Also, the velodyne could perhaps be called something like top_lidar3d to be more consistent with the naming of the other sensors.

**Comment by manuelgitgomes** [comment]
Done
